apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connections-microservice
  name: udaconnect-connections-microservice
spec:
  ports:
  - name: "5000"
    nodePort: 30003
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    service: udaconnect-connections-microservice
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connections-microservice
  name: udaconnect-connections-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connections-microservice
  strategy: {}
  template:
    metadata:
      labels:
        service: udaconnect-connections-microservice
    spec:
      containers:
      - image: nafisehnamazypour/udaconnect-connections-microservice:latest
        name: udaconnect-connections-microservice
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
