apiVersion: v1
kind: Service
metadata:
  labels:
    app: udaconnect-location-generator-service
  name: udaconnect-location-generator-service
spec:
  ports:
  - name: 5005-5005
    nodePort: 30005
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: udaconnect-location-generator-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udaconnect-location-generator-service
  name: udaconnect-location-generator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-location-generator-service
  template:
    metadata:
      labels:
        app: udaconnect-location-generator-service
    spec:
      containers:
      - image: nafisehnamazypour/udaconnect-location-generator-service:latest
        name: udaconnect-location-generator-service
        imagePullPolicy: Always
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
      restartPolicy: Always
